# Generated by Django 4.1.6 on 2023-04-06 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLevel01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Основное Меню',
                'verbose_name_plural': 'Основное Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuLevel02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.menulevel01', verbose_name='Категория меню')),
            ],
            options={
                'verbose_name': 'Меню 2 уровня',
                'verbose_name_plural': 'Меню 2 уровня',
            },
        ),
        migrations.CreateModel(
            name='MenuLevel03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.menulevel02', verbose_name='Категория меню')),
            ],
            options={
                'verbose_name': 'Меню 3 уровня',
                'verbose_name_plural': 'Меню 3 уровня',
            },
        ),
    ]
